# Generated by Django 4.2.3 on 2023-09-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations_images", "0003_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.ImageField(
                default="places/default_place_image.jpg", upload_to="attachments"
            ),
        ),
    ]
