# Generated by Django 4.2.3 on 2023-09-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations_images", "0004_alter_attachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                default="places/default_place_image.jpg", upload_to="attachments"
            ),
        ),
    ]
