# Generated by Django 4.2.3 on 2023-09-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations_images", "0005_alter_attachment_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attachment",
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.FileField(
                default="places/default_place_image.jpg", upload_to="places"
            ),
        ),
    ]
