# Generated by Django 4.2.3 on 2023-09-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations_images", "0006_delete_attachment_alter_images_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.URLField(),
        ),
    ]
