# Generated by Django 4.2.3 on 2023-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations_images", "0007_alter_images_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.FileField(
                default="places/default_place_image.jpg", upload_to="places"
            ),
        ),
    ]
