version: '3.9'

services:
  web:
    build: .
    command: bash -c "python src/manage.py makemigrations && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8002"
    container_name: trip_assistant
    volumes:
      - .:/trip_assistant
    ports:
      - "8002:8002"
    depends_on:
      - db
  db:
    container_name: postgresql_db
    image: postgres:15
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
    ports:
      - "5432:5432"
