# Generated by Django 4.2.3 on 2023-09-02 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="stars",
        ),
    ]
