# Generated by Django 4.2.3 on 2023-09-04 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_remove_reviews_stars"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Images",
        ),
    ]
