# Generated by Django 4.2.3 on 2023-09-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_delete_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="stars",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
