# Generated by Django 4.2.3 on 2023-09-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_delete_images"),
        ("users", "0007_remove_reviews_location_remove_reviews_user_and_more"),
        ("reviews", "0004_reviews_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="location",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="user",
            field=models.ForeignKey(
                help_text="author of the review",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
