# Generated by Django 4.2.3 on 2023-08-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_profile_bio_remove_profile_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="user_profile/default.jpg", upload_to="user_profile"
            ),
        ),
    ]
