# Generated by Django 4.2.3 on 2023-08-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_rename_country_location_city_and_more"),
        ("users", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="location",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="reviews",
            name="location",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.location",
            ),
        ),
    ]
