# Generated by Django 4.2.3 on 2023-08-25 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_images_location_reviews_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="place",
        ),
        migrations.AlterField(
            model_name="reviews",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
