# Generated by Django 4.2.3 on 2023-08-25 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_reviews_place_alter_reviews_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
