# Generated by Django 4.2.3 on 2023-09-01 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_images_date_posted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="location",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="user",
        ),
        migrations.DeleteModel(
            name="Images",
        ),
        migrations.DeleteModel(
            name="Reviews",
        ),
    ]
