# Generated by Django 4.2.3 on 2023-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_reviews_location_remove_reviews_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(
                default="user_profile/default.jpg", upload_to="user_profile"
            ),
        ),
    ]
