# Generated by Django 4.2.3 on 2023-08-22 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="city",
            new_name="location_name",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="place",
            new_name="place_type",
        ),
    ]
