# Generated by Django 4.2.3 on 2023-08-24 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_rename_city_location_location_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="country",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="zipcode",
            new_name="postcode",
        ),
        migrations.RemoveField(
            model_name="location",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="location",
            name="longitude",
        ),
    ]
