# Generated by Django 4.2.3 on 2023-08-26 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_rename_country_location_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["location_name"]},
        ),
    ]
