# Generated by Django 4.2.3 on 2023-09-05 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_images"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Images",
        ),
    ]
